name: Push to GCR and Deploy GitHub Action
on:
  push
jobs:
  build-and-push-to-gcr-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
      
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: long-star-141310
          image_name: myimage
          image_tag: latest
          dockerfile: Dockerfile
          
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_KEY }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0.8.0'
        with:
          service: 'myimage'
          image: 'gcr.io/long-star-141310/myimage'
          region: 'us-central1-c'
          project_id: 'long-star-141310'
          
          
